use_frameworks!

platform :ios, '8.0'

target 'ZHShowLoading_Example' do
  pod 'ZHShowLoading', :path => '../'

  target 'ZHShowLoading_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
